name = "SleepyTree"
uuid = "580d32d3-afef-4a50-9d43-7715427cf55e"
authors = ["Valencia David"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
